const service = require('../services/person.service');
const { getRequestUser, hasPrivilege, requirePrivilegeInline } = require('../middleware/privilege.middleware');

const PRIVILEGE_KEY = 'person_registry';
function statusFromError(error) { return Number(error?.statusCode || error?.status || 500); }
function publicPerson(person = {}) { return { id: person.id, full_name: person.full_name, preferred_name: person.preferred_name, phone_number: person.phone_number, email: person.email, dsd: person.dsd, gnd: person.gnd, address: person.address }; }
async function requireAnyPrivilege(request, reply, allowed = []) { const identifier = getRequestUser(request); if (!identifier) { reply.status(401).send({ success: false, message: request.authError ? 'Invalid or expired authentication token' : 'Authentication required' }); return false; } for (const [privilegeKey, action] of allowed) { if (await hasPrivilege(identifier, privilegeKey, action)) return true; } const required = allowed.map(([key, action]) => `${key}:${action}`).join(' or '); reply.status(403).send({ success: false, message: `Access denied. Required privilege: ${required}` }); return false; }
const PERSON_SEARCH_ALLOWED = [[PRIVILEGE_KEY, 'view'], ['vwmc_management', 'create'], ['vwmc_management', 'update'], ['intervention_progress_update', 'create'], ['intervention_progress_update', 'update'], ['volunteer_organisation_management', 'update']];
const PERSON_CREATE_ALLOWED = [[PRIVILEGE_KEY, 'create'], ['vwmc_management', 'create'], ['vwmc_management', 'update'], ['intervention_progress_update', 'create'], ['intervention_progress_update', 'update']];

async function personRoutes(fastify) {
  fastify.get('/public/persons/search', async (request) => { const q = String(request.query?.q || '').trim(); if (q.length < 3) return { success: true, persons: [] }; const persons = await service.searchPersons({ q, limit: Math.min(Number(request.query?.limit || 10), 10) }); return { success: true, persons: persons.map(publicPerson) }; });
  fastify.post('/public/persons', async (request, reply) => { try { const body = request.body || {}; const person = await service.createPerson({ full_name: body.full_name, preferred_name: body.preferred_name, phone_number: body.phone_number || body.phone, email: body.email, dsd: body.dsd, gnd: body.gnd, address: body.address }); return reply.status(201).send({ success: true, person: publicPerson(person) }); } catch (error) { return reply.status(statusFromError(error)).send({ success: false, message: error.message || 'Unable to create person' }); } });
  fastify.get('/persons/search', async (request, reply) => { if (!await requireAnyPrivilege(request, reply, PERSON_SEARCH_ALLOWED)) return; const persons = await service.searchPersons({ q: request.query?.q || '', limit: request.query?.limit || 20 }); return { success: true, persons }; });
  fastify.post('/persons/detect-duplicates', async (request, reply) => { if (!await requireAnyPrivilege(request, reply, PERSON_SEARCH_ALLOWED)) return; const matches = await service.detectPossibleDuplicates(request.body || {}); return { success: true, matches }; });
  fastify.get('/persons/:id/profile', async (request, reply) => { if (!await requirePrivilegeInline(request, reply, PRIVILEGE_KEY, 'view')) return; const profile = await service.getPersonProfile(request.params.id); if (!profile) return reply.status(404).send({ success: false, message: 'Person not found' }); return { success: true, profile }; });
  fastify.get('/persons/:id', async (request, reply) => { if (!await requirePrivilegeInline(request, reply, PRIVILEGE_KEY, 'view')) return; const person = await service.getPerson(request.params.id); if (!person) return reply.status(404).send({ success: false, message: 'Person not found' }); return { success: true, person }; });
  fastify.post('/persons', async (request, reply) => { if (!await requireAnyPrivilege(request, reply, PERSON_CREATE_ALLOWED)) return; try { const person = await service.createPerson(request.body || {}); return reply.status(201).send({ success: true, person }); } catch (error) { return reply.status(statusFromError(error)).send({ success: false, message: error.message || 'Unable to create person' }); } });
  fastify.put('/persons/:id', async (request, reply) => { if (!await requirePrivilegeInline(request, reply, PRIVILEGE_KEY, 'update')) return; try { const person = await service.updatePerson(request.params.id, request.body || {}); if (!person) return reply.status(404).send({ success: false, message: 'Person not found' }); return { success: true, person }; } catch (error) { return reply.status(statusFromError(error)).send({ success: false, message: error.message || 'Unable to update person' }); } });
  fastify.delete('/persons/:id', async (request, reply) => { if (!await requirePrivilegeInline(request, reply, PRIVILEGE_KEY, 'delete')) return; try { const person = await service.updatePerson(request.params.id, { status: 'deleted' }); if (!person) return reply.status(404).send({ success: false, message: 'Person not found' }); return { success: true, deleted: request.params.id }; } catch (error) { return reply.status(statusFromError(error)).send({ success: false, message: error.message || 'Unable to delete person' }); } });
  fastify.post('/persons/:id/link-user', async (request, reply) => { if (!await requirePrivilegeInline(request, reply, PRIVILEGE_KEY, 'update')) return; try { const person = await service.linkPersonToUser(request.params.id, request.body?.linked_user_id); if (!person) return reply.status(404).send({ success: false, message: 'Person not found' }); return { success: true, person }; } catch (error) { return reply.status(statusFromError(error)).send({ success: false, message: error.message || 'Unable to link person to user' }); } });
  fastify.post('/persons/:id/promote-user', async (request, reply) => { if (!await requirePrivilegeInline(request, reply, PRIVILEGE_KEY, 'update')) return; if (!await requirePrivilegeInline(request, reply, 'user_management_settings', 'create')) return; try { const result = await service.promotePersonToUser(request.params.id, request.body || {}); return reply.status(201).send({ success: true, message: 'System user created and linked.', ...result }); } catch (error) { return reply.status(statusFromError(error)).send({ success: false, message: error.message || 'Unable to promote person to user' }); } });
}
module.exports = personRoutes;
