INSERT INTO public.gis_layers (
    layer_key,
    layer_name,
    category,
    api_url,
    source_id,
    fill_layer_id,
    line_layer_id,
    popup_type,
    default_visible,
    min_zoom,
    max_zoom,
    fill_color,
    fill_opacity,
    line_color,
    line_width,
    sort_order,
    table_name,
    geom_column,
    active
)
VALUES (
    'vwmc_locations',
    'VWMC Locations',
    'Community Participation',
    '/api/vwmc/committees.geojson',
    'source-vwmc-locations',
    'layer-vwmc-locations-circle',
    NULL,
    'vwmc_locations',
    true,
    0,
    22,
    '#14b8a6',
    0.9,
    '#ffffff',
    2,
    910,
    'vwmc_committees',
    'geom',
    true
)
ON CONFLICT (layer_key)
DO UPDATE SET
    layer_name = EXCLUDED.layer_name,
    category = EXCLUDED.category,
    api_url = EXCLUDED.api_url,
    source_id = EXCLUDED.source_id,
    fill_layer_id = EXCLUDED.fill_layer_id,
    line_layer_id = EXCLUDED.line_layer_id,
    popup_type = EXCLUDED.popup_type,
    default_visible = true,
    fill_color = EXCLUDED.fill_color,
    fill_opacity = EXCLUDED.fill_opacity,
    line_color = EXCLUDED.line_color,
    line_width = EXCLUDED.line_width,
    sort_order = EXCLUDED.sort_order,
    active = true;
