INSERT INTO public.gis_layers (
    layer_key,
    layer_name,
    category,
    api_url,
    source_id,
    fill_layer_id,
    line_layer_id,
    popup_type,
    default_visible,
    min_zoom,
    max_zoom,
    fill_color,
    fill_opacity,
    line_color,
    line_width,
    sort_order,
    table_name,
    geom_column,
    active
)
VALUES (
    'community_complaints',
    'Community Complaints',
    'community_participation',
    '/api/community-reports.geojson',
    'source_community_complaints',
    'layer_community_complaints_circle',
    NULL,
    'community_complaints',
    true,
    0,
    22,
    '#ef4444',
    0.85,
    '#ffffff',
    2,
    900,
    'community_issue_reports',
    'geom',
    true
)
ON CONFLICT (layer_key)
DO UPDATE SET
    layer_name = EXCLUDED.layer_name,
    category = EXCLUDED.category,
    api_url = EXCLUDED.api_url,
    source_id = EXCLUDED.source_id,
    fill_layer_id = EXCLUDED.fill_layer_id,
    line_layer_id = EXCLUDED.line_layer_id,
    popup_type = EXCLUDED.popup_type,
    default_visible = EXCLUDED.default_visible,
    fill_color = EXCLUDED.fill_color,
    fill_opacity = EXCLUDED.fill_opacity,
    line_color = EXCLUDED.line_color,
    line_width = EXCLUDED.line_width,
    sort_order = EXCLUDED.sort_order,
    active = true;
